import type { Metadata } from "next";
import { Libre_Baskerville, Geist_Mono } from "next/font/google";
import "./globals.css";


const libreBaskerville = Libre_Baskerville({
    variable: "--font-libre-baskerville",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
          <link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96"/>
          <link rel="icon" type="image/svg+xml" href="/favicon/favicon.svg"/>
          <link rel="shortcut icon" href="/favicon/favicon.ico"/>
          <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png"/>
          <meta name="apple-mobile-web-app-title" content="AbacoDerma"/>
          <link rel="manifest" href="/favicon/site.webmanifest"/>

          <script src="https://cdn.usefathom.com/script.js" data-site="YUSNIMHU" defer></script>

      </head>
      <body
          className={`${libreBaskerville.variable} ${geistMono.variable} antialiased max-w-7xl mx-3 lg:m-auto`}
      >
      {children}
      </body>
      </html>
  );
}
