// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  boka: dynamic(() => import("./Boka")),
  card_grid: dynamic(() => import("./CardGrid")),
  children: dynamic(() => import("./Children")),
  hafa_samband: dynamic(() => import("./HafaSamband")),
  hero: dynamic(() => import("./Hero")),
  mailchimp_signup: dynamic(() => import("./MailchimpSignup")),
  menu_item: dynamic(() => import("./MenuItem")),
  sub_menu_item: dynamic(() => import("./SubMenuItem")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
