// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  children: dynamic(() => import("./Children")),
  card_grid: dynamic(() => import("./CardGrid")),
  hero: dynamic(() => import("./Hero")),
  menu_item: dynamic(() => import("./MenuItem")),
  sub_menu_item: dynamic(() => import("./SubMenuItem")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
